apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}
  labels:
    name: {{ .Values.servicename }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.servicename }}
      app: {{ .Values.servicename }}
  template:
    metadata:
      labels:
        name: {{ .Values.servicename }}
        app: {{ .Values.servicename }}
    spec:
      containers:
      - name: {{ .Values.servicename }}
        image: {{ .Values.image}} 
        env:
        - name: apikey
          value: {{ .Values.apikey }}
        ports:
        - name: {{ .Values.servicename }}
          containerPort: {{ .Values.service.targetPort }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     