apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}
  labels:
    name: {{ .Values.servicename }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.servicename }}
      app: {{ .Values.servicename }}
  template:
    metadata:
      labels:
        name: {{ .Values.servicename }}
        app: {{ .Values.servicename }}
        app.kubernetes.io/name: {{ .Values.servicename }}
        app.kubernetes.io/instance: {{ .Values.servicename }}
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: demoserviceapps
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/build_version: {{ .Values.build }}
        app.kubernetes.io/version: {{ .Values.release }}
    spec:
      containers:
      - name: {{ .Values.servicename }}
        image: {{ .Values.image }} 
        env:
        - name: apikey
          value: {{ .Values.apikey }}
        - name: KEPTN_PROJECT
          value: {{ .Chart.Name }}
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: KEPTN_SERVICE
          value: {{ .Values.servicename }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"     
        ports:
        - name: {{ .Values.servicename }}
          containerPort: {{ .Values.service.targetPort }}
