apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.servicename }}
  labels:
    name: {{ .Values.servicename }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Values.servicename }}
      app: {{ .Values.servicename }}
  template:
    metadata:
      labels:
        name: {{ .Values.servicename }}
        app: {{ .Values.servicename }}
        app.kubernetes.io/name: {{ .Values.SERVICE_PLACEHOLDER_C.service.name }}
        app.kubernetes.io/instance: "{{ .Values.SERVICE_PLACEHOLDER_C.service.name }}-{{ .Values.SERVICE_PLACEHOLDER_C.deployment.name }}"
        app.kubernetes.io/component: api
        app.kubernetes.io/part-of: "demoserviceapps"
        app.kubernetes.io/managed-by: Keptn
        app.kubernetes.io/version: {{ (split ":" .Values.image)._1 | default "latest" }}
    spec:
      containers:
      - name: {{ .Values.servicename }}
        image: {{ .Values.image}} 
        env:
        - name: apikey
          value: {{ .Values.apikey }}
        ports:
        - name: {{ .Values.servicename }}
          containerPort: {{ .Values.service.targetPort }}
        env:
        ...
        - name: KEPTN_PROJECT
          value: "{{ .Chart.Name }}"
        - name: KEPTN_STAGE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: KEPTN_SERVICE
          value: "{{ .Values.SERVICE_PLACEHOLDER_C.service.name }}"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     