---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoappservice
  labels:
    name: news
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      name: news
      app: news
  template:
    metadata:
      labels:
        name: news
        app: news
    spec:
      containers:
      - name: darth-vader
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
        - name: APIKEY
          value: "{{ .Values.apikey }}"
        ports:
        - name: news
          containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
     