apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
      app: news