apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http-port":"HTTP"}'
  labels:
    app: {{ .Values.servicename }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.servicename }}
  ports:
  - name: http-port
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}