---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicename }}
  labels:
    name: demoserviceapps
    app: demoserviceapps
spec:
  type: ClusterIP
  ports:
  - name: http
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: demoserviceapps