apiVersion: "spec.keptn.sh/0.2.2"
kind: "Shipyard"
metadata:
  name: "shipyard-demoserviceapps"
spec:
  stages:
    - name: "dev"
      sequences:
            - name: "delivery"
              tasks:
                - name: "deployment"
                  properties:
                    deploymentstrategy: "blue_green_service"
                - name: "test"
                  properties:
                    teststrategy: "functional"
                - name: "evaluation"
                - name: "release"
            - name: "delivery-direct"
              tasks:
                - name: "deployment"
                  properties:
                    deploymentstrategy: "blue_green_service"
                - name: "test"
                  properties:
                    teststrategy: "functional"
                - name: "evaluation"
                - name: "release"
    - name: "staging"
      sequences:
            - name: "delivery"
              triggeredOn:
               - event: dev.delivery
              tasks:
                - name: "deployment"
                  properties:
                    deploymentstrategy: "blue_green_service"
                - name: "test"
                  properties:
                    teststrategy: "functional"
                - name: "evaluation"
                - name: "release"
    - name: production
      sequences:
        - name: "delivery"
          triggeredOn:
            - event: staging.delivery
          tasks:
          - name: approval
            properties:
              pass: manual
              warning: manual
          - name: deployment
            properties:
                deploymentstrategy: "blue_green_service"
          - name: release
        - name: rollback
          triggeredOn:
          - event: production.delivery.finished
            selector:
              match:
                result: failed
          tasks:
          - name: rollback
        - name: remediation
          tasks:
          - name: remediation
          - name: evaluation
            triggeredAfter: "10m"
