name: Docker Image CI

on:
  push:
    branches: 
    - main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: Stockopedia/action-get-changed-files@v1.2
      - name: get-changed-folders
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file fbi/Dockerfile --tag my-image-name:$(date +%s)
