name: Docker Image CI

on:
  push:
    branches: 
    - main
jobs:

  build-run-test:

    runs-on: ubuntu-latest

    steps:
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true
          format: csv
      - name: list changed folders
        run: echo ${{ steps.get_changed.outputs.changed }}
      - uses: actions/checkout@v2
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: Build the Docker image
        run:  docker build . --file ${{ steps.get_changed.outputs.changed }}/Dockerfile --tag ${{ steps.get_changed.outputs.changed }}:${{ GITHUB.SHA }}
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: run the Docker image
        run:  docker run --name ${{ steps.get_changed.outputs.changed }} -d -p 5000:8080 ${{ steps.get_changed.outputs.changed }}:${{ GITHUB.SHA }}
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: get public ip
        uses: haythem/public-ip@v1.2
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: run test
        uses: fjogeleit/http-request-action@v1.8.1
        with:
            url: http://${{ steps.get public ip.outputs.ipv4 }}:5000/data
            method: get
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: Docker stop
        run:  docker stop ${{ steps.get_changed.outputs.changed }}
      - if: steps.get_changed.outputs.changed == 'fbi' || steps.get_changed.outputs.changed == 'frauddetection'
        name: Docker Remove
        run:  docker rm ${{ steps.get_changed.outputs.changed }}
