name: Docker Image CI

on:
  push:
    branches: 
    - main
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: Stockopedia/action-get-changed-files@v1
        id: get_changed
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore: "**/+(.github)"
          foldersOnly: true
          format: csv
      - name: Echo changed files
        run: echo ${{ steps.get_changed.outputs.changed }}
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: if [ "${{ steps.get_changed.outputs.changed }}" == "fbi" ] || [ "${{ steps.get_changed.outputs.changed }}" == "frauddetection" ] || [ "${{ steps.get_changed.outputs.changed }}" == "news" ] || [ "${{ steps.get_changed.outputs.changed }}" == "function" ]; then docker build . --file ${{ steps.get_changed.outputs.changed }}/Dockerfile --tag my-image-name:$(date +%s); else echo "no files in containers were changed"; fi



