name: Docker Image CI

on:
  push:
    branches: 
    - main 'demoserviceapps/fbi'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file fbi/Dockerfile --tag my-image-name:$(date +%s)
